### ISSUE TITLE
Adding more commands 

### ISSUE THREAD

**Issue by moshivji** [gmazoyer/looking-glass#158] opened 2021-06-24 13:15 UTC
Hi

I have tried to add more commands to use with Juniper routers. I have edited both eh config.defaults file and the juniper routers file but keep getting error.

Is it possible to add more commands to this ?

**Comment by gmazoyer** [comment] 2022-02-09 13:30
Duplicate of #84

**Closed by gmazoyer** 2022-02-09 13:30 UTC
